version: '3'
services:
    app-1:
        container_name: app-1
        build:
            context: ./
        expose:
            - '8080'
        environment:
            - SERVER_PORT=8080
            - NETOLOGY_PROFILE_DEV=false
        networks:
            - backend

    app-2:
        container_name: app-2
        build:
            context: ./
        expose:
            - '8081'
        environment:
            - SERVER_PORT=8081
            - NETOLOGY_PROFILE_DEV=true
        networks:
            - backend

    proxy:
        container_name: proxy
        image: nginx
        volumes:
            -   ${PWD}/src/main/resources/static/signing:/usr/share/nginx/html/signing
            -   ${PWD}/config:/etc/nginx/conf.d
        ports:
            -   '9999:80'
        depends_on:
            -   app-1
            -   app-2
        networks:
            - backend

networks:
    backend: