version: '3'
services:
    app:
        container_name: app
        build:
            context: ./
        networks:
            - backend

    proxy:
        container_name: proxy
        image: nginx
        volumes:
            -   ${PWD}/src/main/resources/static/signing:/usr/share/nginx/html/signing
            -   ${PWD}/config:/etc/nginx/conf.d
        ports:
            -   '9999:80'
        depends_on:
            -   app
        networks:
            - backend

networks:
    backend: